spring:
    datasource:
        name: crmdb
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/crmdb?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 111111
        driver-class-name: com.mysql.jdbc.Driver

    mvc:
      view:
        prefix: classpath:/templates/
        suffix: .html

    thymeleaf:
      mode: HTML5
      encoding: utf-8
      servlet:
        content-type: text/html
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:/mybatis/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.crm.entity
  configuration:
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
